# Generated by Django 3.1.2 on 2020-12-06 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201206_0940'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
